[package]
name = "highlight_to_clipboard_ubuntu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
shellexpand = "3.1.0"
